### ISSUE TITLE
📍Roadmap of Pero

### ISSUE THREAD

**Issue by h-a-n-a** [h-a-n-a/pero#1]
# Preview Version

## Route
- [X] route parse
- [X] command generation
- [ ] detailed error messages
- [ ] async
- [ ] unit test

## Option
- [x] option parse
- [x] input validation
- [x] required
- [ ] variadic args
- [ ] internal option with option overriding
- [ ] unit test

## Argument
- [x] input validation
- [x] required
- [ ] unit test

## UI
- [ ] better UI
- [ ] custom renderer

## Type
- [ ] better type inference

## CLI
- [x] compilation
- [ ] watch
